name: samples
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - vector
  - split
  - attoparsec
  - aeson

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  main01:
    main: Main01.hs
    source-dirs: app

  main02:
    main: Main02.hs
    source-dirs: app

  main03:
    main: Main03.hs
    source-dirs: app

  main04:
    main: Main04.hs
    source-dirs: app

  main05:
    main: Main05.hs
    source-dirs: app

  main06:
    main: Main06.hs
    source-dirs: app

  main07:
    main: Main07.hs
    source-dirs: app

  main08:
    main: Main08.hs
    source-dirs: app
