name: samples
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - containers

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  main01:
    main: Main01.hs
    source-dirs: app

  main02:
    main: Main02.hs
    source-dirs: app

  main03:
    main: Main03.hs
    source-dirs: app

  main04:
    main: Main04.hs
    source-dirs: app

  main05:
    main: Main05.hs
    source-dirs: app
