name: samples
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - transformers
  - array
  - mtl
  - lifted-base

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  main01:
    main: Main01.hs
    source-dirs: app

  main02:
    main: Main02.hs
    source-dirs: app

  main03:
    main: Main03.hs
    source-dirs: app

  main04:
    main: Main04.hs
    source-dirs: app

  main05:
    main: Main05.hs
    source-dirs: app

  main06:
    main: Main06.hs
    source-dirs: app

  main07:
    main: Main07.hs
    source-dirs: app

  main08:
    main: Main08.hs
    source-dirs: app

  main09:
    main: Main09.hs
    source-dirs: app

  main10:
    main: Main10.hs
    source-dirs: app

  main11:
    main: Main11.hs
    source-dirs: app

  main12:
    main: Main12.hs
    source-dirs: app

  main13:
    main: Main13.hs
    source-dirs: app

  main14:
    main: Main14.hs
    source-dirs: app
