name: samples
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5

executables:
  main01:
    main: Main01.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-import-lists

  main02:
    main: Main02.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-import-lists
