name: hjq
version: 0.1.0.0

ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - text
  - bytestring
  - aeson
  - aeson-pretty
  - lens
  - lens-aeson
  - vector
  - unordered-containers
  - errors

library:
  source-dirs: src

executables:
  hjq-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hjq

tests:
  hjq-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hjq
      - HUnit
